#!/usr/bin/env bash
# redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sed -i '48i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=XPwo6giiZ_o permanent;\n}\n' /etc/nginx/sites-available/default
sudo service nginx restart