#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# for the 9th iteration, displays Holberton School and then Hi on a new line
n=0
while (( n++ < 10 )); do
	if (( n == 9))
	then
		echo "Holberton School"
		echo "Hi"
	else
		echo "Holberton School"
	fi
done
